# Generated by Django 2.2.5 on 2019-09-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('lat', models.CharField(max_length=20, null=True, verbose_name='Lat')),
                ('long', models.CharField(max_length=20, null=True, verbose_name='Long')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car')),
            ],
        ),
    ]
