# Generated by Django 2.2.5 on 2019-09-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providertruck'),
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTrackers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('lat', models.CharField(max_length=20, null=True, verbose_name='Lat')),
                ('long', models.CharField(max_length=20, null=True, verbose_name='Long')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('provider_truck_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.ProviderTruck')),
            ],
            options={
                'verbose_name': 'Provider Position',
                'verbose_name_plural': 'Providers Positions',
                'ordering': ['id'],
            },
        ),
    ]
