# Generated by Django 2.2.5 on 2019-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mat', models.CharField(max_length=10, verbose_name='License Plate')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('condition', models.CharField(choices=[('new', 'NEW'), ('used', 'USED')], default='used', max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('odometer', models.IntegerField()),
                ('observations', models.TextField(max_length=300, null=True)),
                ('cartype', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
    ]
