# Generated by Django 2.2.5 on 2019-09-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='NIPC')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('telephone1', models.CharField(max_length=12, verbose_name='Telephone')),
                ('telephone2', models.CharField(max_length=12, verbose_name='Mobile Phone')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('zipCode', models.CharField(max_length=8, verbose_name='Zip Code')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('personType', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='providers.PersonType')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderFinance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=80, verbose_name='Bank Name')),
                ('iban', models.CharField(max_length=60, verbose_name='Iban')),
                ('swift', models.CharField(max_length=10, verbose_name='Swift')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('paymentType', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='providers.PaymentType')),
                ('provider_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider')),
            ],
        ),
    ]
