# Generated by Django 2.2.5 on 2019-09-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='persontype',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='provider',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='providerfinance',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='nif',
            field=models.CharField(max_length=9, unique=True, verbose_name='NIPC'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='personType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='providers.PersonType'),
        ),
        migrations.AlterField(
            model_name='providerfinance',
            name='paymentType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='providers.PaymentType'),
        ),
    ]
