# Generated by Django 2.2.5 on 2019-09-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTruck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('truckMat', models.CharField(max_length=10, verbose_name='Truck License Plate')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('truckTelephone', models.CharField(max_length=12, verbose_name='Drive Telephone')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='providers.Provider')),
            ],
        ),
    ]
