# Generated by Django 2.2.5 on 2019-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20190919_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=120, verbose_name='Address'),
        ),
    ]
